version: 2.1

# Define the Node.js executor
executors:
  node-executor:
    docker:
      - image: cimg/node:22.14
    working_directory: ~/project

# Define reusable commands
commands:
  install-pnpm:
    description: 'Install pnpm package manager'
    steps:
      - run:
          name: Install pnpm
          command: |
            corepack enable
            corepack prepare pnpm@10.6.2 --activate

  install-dependencies:
    description: 'Install project dependencies with pnpm'
    steps:
      - restore_cache:
          keys:
            - pnpm-deps-v1-{{ checksum "pnpm-lock.yaml" }}
            - pnpm-deps-v1-
      - run:
          name: Install dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: pnpm-deps-v1-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.local/share/pnpm/store

# Define jobs
jobs:
  lint:
    executor: node-executor
    steps:
      - checkout
      - install-pnpm
      - install-dependencies
      - run:
          name: Run linting
          command: pnpm lint

  test:
    executor: node-executor
    steps:
      - checkout
      - install-pnpm
      - install-dependencies
      - run:
          name: Run type checking
          command: pnpm tsc --noEmit
      - run:
          name: Run tests
          command: pnpm test --run

  build:
    executor: node-executor
    steps:
      - checkout
      - install-pnpm
      - install-dependencies
      - run:
          name: Build application
          command: pnpm build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .next/

# Define workflows
workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
