/**
 * Collection d'idées de jeux simples pour PICO-8
 * Chaque idée se concentre sur des mécaniques classiques et réalisables
 */
export const GAME_IDEAS = [
  'Un petit serpent qui mange des pommes et grandit dans un jardin',
  'Une grenouille qui saute sur des nénuphars pour traverser la rivière',
  'Des blocs colorés qui tombent et qu\'il faut empiler intelligemment',
  'Une balle qui rebondit pour détruire des briques multicolores',
  'Un pacman affamé qui mange des points en évitant les fantômes',
  'Une voiture qui zigzague entre les obstacles sur l\'autoroute',
  'Un oiseau qui vole entre les tuyaux sans les toucher',
  'Des bonbons qui tombent du ciel à attraper dans un panier',
  'Un petit héros qui saute de plateforme en plateforme',
  'Une fusée qui tire sur des envahisseurs venus de l\'espace',
  'Un labyrinthe où il faut trouver la sortie sans se perdre',
  'Des gemmes brillantes cachées dans une mine à collecter',
  'Un chat qui court et saute pour attraper des souris',
  'Une tortue qui évite les obstacles en roulant vers l\'arrivée',
  'Des bulles colorées à faire éclater en les regroupant',
  'Un pingouin qui glisse sur la glace en collectant des poissons',
  'Une abeille qui butine les fleurs sans toucher les épines',
  'Un robot qui pousse des caisses pour résoudre des énigmes',
  'Une princesse qui court dans son château en évitant les pièges',
  'Un vaisseau spatial qui navigue entre les météorites',
  'Un escargot qui grimpe lentement mais sûrement vers le sommet',
  'Des dominos qui tombent en chaîne à déclencher au bon moment',
  'Un poulpe qui nage dans les profondeurs en évitant les méduses',
  'Une citrouille qui roule en collectant des bonbons d\'Halloween',
  'Un pinball avec des flippers pour faire rebondir la balle',
  'Un hamster qui court dans sa roue en sautant les obstacles',
  'Des cartes à retourner pour trouver les paires identiques',
  'Un skieur qui descend la pente en slalomant entre les sapins',
  'Une coccinelle qui se balade sur les feuilles sans tomber',
  'Un dinosaure qui court en sautant par-dessus les cactus',
  'Des lettres qui tombent pour former des mots rapidement',
  'Un phoque qui jongle avec des balles sur son museau',
  'Une flèche qui vole droit vers la cible au centre',
  'Un crabe qui marche de côté sur la plage en évitant les vagues',
  'Des blocs de couleur à aligner pour les faire disparaître',
  'Un manchot qui glisse sur le ventre en collectant des sardines',
  'Une bille qui roule dans un parcours plein de virages',
  'Un écureuil qui saute d\'arbre en arbre pour ramasser des glands',
  'Des tuyaux à connecter pour faire couler l\'eau jusqu\'au bout',
  'Un fantôme qui traverse les murs en collectant des pièces',
  'Une voiture qui fait des loopings sur un circuit fou',
  'Un canard qui nage dans l\'étang en évitant les nénuphars',
  'Des chiffres qui s\'additionnent pour atteindre le bon total',
  'Un papillon qui voltige de fleur en fleur sans se fatiguer',
  'Une boule qui roule en bas de la montagne en évitant les rochers',
  'Des fourmis qui marchent en file indienne vers la fourmilière',
  'Un singe qui se balance de liane en liane dans la jungle',
  'Des étoiles qui brillent et qu\'il faut relier entre elles',
  'Un poisson qui nage dans l\'aquarium en évitant les requins',
  'Une araignée qui tisse sa toile pour attraper les mouches',
  'Des pommes qui tombent de l\'arbre à réceptionner dans le panier',
  'Un lapin qui bondit dans les champs en évitant les trous',
  'Une goutte d\'eau qui descend le long de la vitre en zigzag',
  'Des cercles concentriques à toucher pile au bon moment',
  'Un hérisson qui se roule en boule pour rouler plus vite',
  'Une libellule qui vole au-dessus de l\'étang en chassant les moustiques',
  'Des formes géométriques à faire rentrer dans les bons trous',
  'Un ourson qui récolte du miel en évitant les abeilles en colère',
  'Une balle de tennis qui rebondit contre les murs',
  'Des notes de musique qui défilent sur la portée à jouer',
  'Un morse qui plonge sous l\'eau pour attraper des poissons',
  'Une marelle où il faut sauter dans les cases sans marquer la ligne',
  'Des engrenages qui tournent pour faire fonctionner une machine',
  'Un renard qui court dans la forêt en sautant par-dessus les rondins',
  'Une baguette magique qui fait apparaître des étoiles colorées',
  'Des balles de ping-pong qui rebondissent sur les raquettes',
  'Un éléphanteau qui aspire les cacahuètes avec sa trompe',
  'Une corde à sauter qui tourne de plus en plus vite',
  'Des pièces de puzzle à assembler pour former une image',
  'Un raton laveur qui lave ses aliments dans la rivière',
  'Une toupie qui tourne en évitant de tomber du plateau',
  'Des feuilles mortes qui tombent en automne à rattraper',
  'Un koala qui grimpe à l\'eucalyptus pour manger les feuilles',
  'Une raquette de badminton qui renvoie le volant',
  'Des bulles de savon qui s\'envolent et qu\'il faut faire éclater',
  'Un castor qui construit un barrage avec des branches',
  'Une marche qui monte des escaliers un à un',
  'Des dominos alignés à faire tomber dans le bon ordre',
  'Un colibri qui butine en vol stationnaire devant les fleurs',
  'Une pierre qui ricoche sur l\'eau en comptant les rebonds',
  'Des allumettes à disposer pour former des formes géométriques',
  'Un kangourou qui bondit en portant son petit dans sa poche',
  'Une balle de golf qui roule vers le trou en évitant les obstacles',
  'Des triangles, carrés et cercles à trier par couleur',
  'Un phoque qui fait tourner un ballon sur son museau',
  'Une plume qui vole au gré du vent sans toucher le sol',
  'Des perles colorées à enfiler sur un fil dans le bon ordre',
  'Un dé qui roule et s\'arrête sur des chiffres chanceux',
  'Une hirondelle qui vole en formation avec ses copines',
  'Des gouttes de pluie qui tombent dans les flaques',
  'Un yoyo qui monte et descend au bout de sa ficelle',
  'Une coccinelle qui compte ses points noirs dans le miroir',
  'Des dominos colorés à aligner pour créer des motifs',
  'Un chameau qui traverse le désert en évitant les tempêtes de sable',
  'Une balle qui rebondit entre deux raquettes de plus en plus vite',
  'Des graines à planter dans le jardin pour faire pousser des fleurs',
  'Un pingouin qui fait du toboggan sur son ventre',
  'Une cible qui bouge et qu\'il faut toucher avec des fléchettes',
  'Des glaçons qui fondent et qu\'il faut rattraper dans un verre',
  'Un écureuil volant qui plane entre les arbres',
  'Une balle de basket qui rebondit vers le panier',
  'Des pièces de monnaie qui tombent dans la tirelire',
  'Un paresseux qui descend lentement de son arbre',
  'Une corde qui ondule et qu\'il faut faire passer par des anneaux',
  'Des confettis multicolores qui s\'envolent dans les airs',
  'Un ourson panda qui mange des pousses de bambou',
  'Une balle de baseball qui vole vers le gant du receveur',
  'Des flocons de neige uniques qui tombent du ciel',
  'Un poisson-clown qui se cache dans les anémones de mer',
  'Une quille de bowling qui tombe quand la boule arrive',
  'Des pétales de fleurs qui s\'envolent au vent du printemps',
  'Un chat qui ronronne en se roulant dans l\'herbe',
  'Une balle de golf qui roule sur le green vers le trou',
  'Des bulles d\'air qui remontent à la surface de l\'eau',
  'Un morse qui se prélasse au soleil sur son rocher',
  'Une bille qui roule dans un labyrinthe transparent',
  'Des feuilles qui changent de couleur à l\'automne',
  'Un dauphin qui saute hors de l\'eau en faisant des pirouettes',
  'Une balle de tennis qui rebondit de plus en plus haut',
  'Des étoiles filantes qui traversent le ciel nocturne',
  'Un chiot qui court après sa queue en tournant',
  'Une balle de rugby qui rebondit de façon imprévisible',
  'Des gouttes de rosée qui brillent sur les pétales au matin',
  'Un flamant rose qui se tient sur une patte dans l\'étang',
  'Une balle de ping-pong qui rebondit entre les joueurs',
  'Des cristaux de glace qui se forment sur la fenêtre',
  'Un poussin qui picore les graines dans la basse-cour',
  'Une balle de handball qui rebondit contre le mur',
  'Des rayons de soleil qui percent à travers les nuages',
  'Un raton laveur qui trempe ses pattes dans l\'eau claire',
  'Une balle de volley qui passe par-dessus le filet',
  'Des gouttes d\'eau qui perlent sur les feuilles après la pluie',
  'Un petit escargot qui laisse une trace brillante derrière lui',
  'Une balle de cricket qui rebondit sur le terrain',
  'Des arcs-en-ciel qui apparaissent après l\'orage',
  'Un chat qui guette les oiseaux depuis sa fenêtre',
  'Une balle de squash qui rebondit dans tous les sens',
  'Des papillons colorés qui voltigent dans le jardin fleuri',
  'Un chaton qui joue avec une pelote de laine',
  'Une balle de water-polo qui flotte à la surface',
  'Des étincelles qui jaillissent du feu de camp',
  'Un petit renard qui chasse les souris dans les hautes herbes',
  'Une balle de badminton qui vole par-dessus le filet',
  'Des lucioles qui clignotent dans l\'obscurité de la nuit',
  'Un chiot qui rapporte le bâton qu\'on lui a lancé',
  'Une balle de softball qui roule vers la base',
  'Des bulles d\'air qui remontent dans la bouteille renversée',
  'Un petit ours qui pêche les saumons dans la rivière',
  'Une balle de lacrosse qui vole vers le but',
  'Des gouttelettes qui dansent sur la surface de l\'eau',
  'Un hérisson qui se roule en boule quand il a peur',
  'Une balle de polo qui roule sur le terrain',
  'Des étincelles magiques qui s\'échappent de la baguette',
  'Un écureuil qui cache ses noisettes pour l\'hiver',
  'Une balle de hockey qui glisse sur la glace',
  'Des particules de poussière qui dansent dans un rayon de soleil',
  'Un chat qui se faufile silencieusement dans les buissons',
  'Une balle de football américain qui vole en spirale',
  'Des gouttelettes de brume qui flottent au-dessus du lac',
  'Un chiot qui creuse un trou dans le sable de la plage',
  'Une balle de pétanque qui roule vers le cochonnet',
  'Des particules scintillantes qui s\'élèvent de la potion magique',
  'Un chat qui se lèche la patte pour faire sa toilette',
  'Une balle de croquet qui passe sous les arceaux',
  'Des gouttelettes qui s\'accrochent à la toile d\'araignée',
  'Un chaton qui bondit sur les ombres qui bougent',
  'Une balle de bowling qui dévale la piste vers les quilles',
  'Des particules dorées qui tourbillonnent dans l\'air',
  'Un chat qui ronronne en se frottant contre les jambes',
  'Une balle de billard qui rebondit sur les bandes',
  'Des gouttelettes qui tombent du robinet qui fuit',
  'Un chiot qui remue la queue dès qu\'il voit son maître',
  'Une balle de pétanque qui s\'arrête près du but',
  'Des particules colorées qui s\'échappent du feu d\'artifice',
  'Un chat qui observe les poissons dans l\'aquarium',
  'Une balle de flipper qui rebondit partout dans la machine',
  'Des gouttelettes de pluie qui glissent sur la vitre',
  'Un chiot qui court en cercle pour attraper sa queue',
  'Une balle de tennis de table qui fait des allers-retours',
  'Des particules brillantes qui flottent dans l\'eau pétillante',
  'Un chat qui s\'étire longuement en se réveillant',
  'Une boule de neige qui roule et grossit en descendant la pente',
  'Des gouttelettes d\'eau qui sautent sur la surface chaude',
  'Un chiot qui joue à cache-cache derrière les meubles',
  'Une balle en caoutchouc qui rebondit de plus en plus haut',
  'Des particules de sable qui s\'envolent dans le vent du désert',
  'Un chat qui chasse les ombres sur le mur',
  'Une balle de mousse qui rebondit mollement sur le sol',
  'Des gouttelettes qui perlent sur la fourrure du chien mouillé',
  'Un chiot qui découvre la neige pour la première fois',
  'Une balle de caoutchouc qui rebondit en rythme',
  'Des particules de pollen qui dansent dans l\'air printanier',
  'Un chat qui se cache dans un carton trop petit pour lui',
  'Une balle de stress qui se déforme dans la main',
  'Des gouttelettes qui s\'évaporent au soleil du matin',
  'Un chiot qui apprend à donner la patte',
  'Une balle de jonglage qui vole d\'une main à l\'autre',
  'Des particules de poussière d\'étoiles qui brillent dans l\'espace',
  'Un chat qui fait semblant de dormir pour attraper sa proie',
  'Une balle de yoga qui roule lentement sur le tapis',
  'Des gouttelettes de condensation qui se forment sur le verre froid',
  'Un chiot qui découvre son reflet dans le miroir',
  'Une balle de massage qui roule sous le pied',
  'Des particules de neige qui tourbillonnent dans le blizzard',
  'Un chat qui observe les flocons de neige par la fenêtre',
  'Une balle de plage qui rebondit joyeusement sur le sable',
  'Des gouttelettes qui tombent de la stalactite dans la grotte',
  'Un chiot qui apprend à rapporter le journal',
  'Une balle de méditation qui roule dans la main',
  'Des particules de lumière qui dansent dans l\'arc-en-ciel',
  'Un chat qui se prélasse dans un rayon de soleil',
  'Une balle de gymnastique qui rebondit sur le tapis',
  'Des gouttelettes qui se forment à la pointe des feuilles',
  'Un chiot qui découvre les joies de la baignade',
  'Une balle de thérapie qui aide à se détendre',
  'Des particules magiques qui s\'échappent du livre d\'sorts',
  'Un chat qui guette patiemment devant le trou de souris',
  'Une balle de rééducation qui roule sous le pied blessé',
  'Des gouttelettes qui dansent sur la surface de l\'étang',
  'Un chiot qui apprend les règles de la maison',
  'Une balle de relaxation qui se balance doucement',
  'Des particules de bonheur qui flottent dans l\'air',
  'Un chat qui ronronne de contentement dans les bras',
  'Une balle de bien-être qui aide à évacuer le stress',
  'Des gouttelettes de joie qui perlent sur les joues',
  'Un chiot qui découvre le bonheur de la première promenade',
];